[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP235x"
#runner = "elf2uf2-rs -d"
runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv6m-none-eabi" # if you change this, ALSO change rust-toolchain.toml

[env]
DEFMT_LOG = "debug"
